# Generated by Django 6.0 on 2025-12-09 15:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('board_created', 'Board Created'), ('board_updated', 'Board Updated'), ('board_archived', 'Board Archived'), ('board_restored', 'Board Restored'), ('board_member_added', 'Board Member Added'), ('board_member_removed', 'Board Member Removed'), ('list_created', 'List Created'), ('list_updated', 'List Updated'), ('list_moved', 'List Moved'), ('list_archived', 'List Archived'), ('list_restored', 'List Restored'), ('card_created', 'Card Created'), ('card_updated', 'Card Updated'), ('card_moved', 'Card Moved'), ('card_archived', 'Card Archived'), ('card_restored', 'Card Restored'), ('card_completed', 'Card Completed'), ('card_member_added', 'Card Member Added'), ('card_member_removed', 'Card Member Removed'), ('card_label_added', 'Card Label Added'), ('card_label_removed', 'Card Label Removed'), ('card_due_date_set', 'Card Due Date Set'), ('card_due_date_changed', 'Card Due Date Changed'), ('card_due_date_removed', 'Card Due Date Removed'), ('checklist_created', 'Checklist Created'), ('checklist_updated', 'Checklist Updated'), ('checklist_deleted', 'Checklist Deleted'), ('checklist_item_completed', 'Checklist Item Completed'), ('checklist_item_uncompleted', 'Checklist Item Uncompleted'), ('attachment_added', 'Attachment Added'), ('attachment_deleted', 'Attachment Deleted'), ('comment_added', 'Comment Added'), ('comment_updated', 'Comment Updated'), ('comment_deleted', 'Comment Deleted')], max_length=100)),
                ('action_data', models.JSONField(blank=True, help_text='Additional data about the action', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
