# Generated by Django 6.0 on 2025-12-09 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['board'], name='activities_board_i_20443b_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['card'], name='activities_card_id_c702c4_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user'], name='activities_user_id_2fedd2_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-created_at'], name='activities_created_765ec9_idx'),
        ),
    ]
