# Generated by Django 6.0 on 2025-12-09 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='boards.board'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', through='boards.BoardMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardstar',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='boards.board'),
        ),
        migrations.AddField(
            model_name='boardstar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.board'),
        ),
        migrations.AddIndex(
            model_name='boardmember',
            index=models.Index(fields=['board'], name='board_membe_board_i_4a22c9_idx'),
        ),
        migrations.AddIndex(
            model_name='boardmember',
            index=models.Index(fields=['user'], name='board_membe_user_id_aa11b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardmember',
            unique_together={('board', 'user')},
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['workspace'], name='boards_workspa_7c2d99_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['created_by'], name='boards_created_a52851_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['is_archived'], name='boards_is_arch_4640f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardstar',
            unique_together={('board', 'user')},
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['board'], name='labels_board_i_789a0b_idx'),
        ),
    ]
