# Generated by Django 6.0 on 2025-12-09 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_initial'),
        ('cards', '0001_initial'),
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lists.list'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cards.card'),
        ),
        migrations.AddField(
            model_name='cardlabel',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_labels', to='cards.card'),
        ),
        migrations.AddField(
            model_name='cardlabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_labels', to='boards.label'),
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(related_name='cards', through='cards.CardLabel', to='boards.label'),
        ),
        migrations.AddField(
            model_name='cardmember',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardmember',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_members', to='cards.card'),
        ),
        migrations.AddField(
            model_name='cardmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(related_name='assigned_cards', through='cards.CardMember', through_fields=('card', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='cards.card'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cards.checklist'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cards.card'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmention',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='cards.comment'),
        ),
        migrations.AddField(
            model_name='commentmention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['card'], name='attachments_card_id_0adf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='cardlabel',
            index=models.Index(fields=['card'], name='card_labels_card_id_e85f39_idx'),
        ),
        migrations.AddIndex(
            model_name='cardlabel',
            index=models.Index(fields=['label'], name='card_labels_label_i_849880_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardlabel',
            unique_together={('card', 'label')},
        ),
        migrations.AddIndex(
            model_name='cardmember',
            index=models.Index(fields=['card'], name='card_member_card_id_36280f_idx'),
        ),
        migrations.AddIndex(
            model_name='cardmember',
            index=models.Index(fields=['user'], name='card_member_user_id_f885e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardmember',
            unique_together={('card', 'user')},
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['list'], name='cards_list_id_08110b_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['list', 'position'], name='cards_list_id_72174c_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['created_by'], name='cards_created_49cefb_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['due_date'], name='cards_due_dat_243c97_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['card'], name='checklists_card_id_79370d_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['checklist'], name='checklist_i_checkli_c5af2f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['card'], name='comments_card_id_82252d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comments_user_id_8613ff_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmention',
            index=models.Index(fields=['user'], name='comment_men_user_id_6d3c94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentmention',
            unique_together={('comment', 'user')},
        ),
    ]
