# Generated by Django 6.0 on 2025-12-09 15:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mention', 'Mention'), ('assignment', 'Assignment'), ('due_date', 'Due Date'), ('comment', 'Comment'), ('card_moved', 'Card Moved'), ('board_invite', 'Board Invite'), ('workspace_invite', 'Workspace Invite'), ('card_completed', 'Card Completed'), ('checklist_completed', 'Checklist Completed'), ('attachment_added', 'Attachment Added'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='boards.board')),
                ('related_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cards.card')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
